apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  labels:
    reg: secrets
spec:
  containers:
    - name: my-echoserver
      image: docker.io/dnjameshome/my-echoserver:1.0
      ports:
      - containerPort: 8080
  imagePullSecrets:
    - name: regsecret
